schema_version = "1.0.0"

version = "1.0.0"
id = "blender_add_on"
name = "BlenderAddOn"
tagline = "NPR Framework For Rendering 3D -> 2D"
maintainer = "Allocator <>"
type = "add-on"
tags = ["3D View", "Compositing"]
blender_version_min = "4.0.0"
license = [
  "SPDX:GPL-3.0-or-later",
]
